install.packages("ggplot2")
install.packages('data.table')
install.packages('rpart')
library(ggplot2)
library(data.table)
library(rpart)

mydata=as.data.table(diamonds)
dim(mydata)

ggplot(iris,aes(x=Sepal.Length,y=Sepal.Width ,color='red'))+geom_point(size=1)

ggplot(iris,aes(x=Sepal.Length,y=Petal.Length ,color=Species))+geom_point(size=1)

ggplot(iris,aes(x=Species ,y=Sepal.Length,color=Species))+geom_boxplot(size=0.5)

ggplot(iris,aes(x=Petal.Length ))+geom_density(alpha=0.02)+geom_histogram(size=0.5)

ggplot(data=iris[Species=='setosa',],aes(x=Sepal.Length,y=Sepal.Width,color=Species))+geom_point()

ggplot(data=iris[iris$Species=="setosa",],aes(x=Sepal.Length,y=Sepal.Width,color=Species))+geom_point()

ggplot(data=iris[iris$Species=="setosa",],aes(x=Sepal.Length,color=Species))+geom_density()

ggplot(data=iris,aes(x=Species,y=Sepal.Width,color=Species))+geom_boxplot()

ggplot(data=iris,aes(x=Species,y=Sepal.Width,color=Species))+geom_boxplot()

zz<- iris[iris$Species=="setosa",]

str(zz)

ggplot(data=zz,aes(x=Sepal.Length,color=Species))+geom_density()
zz_cutvar <- pmin(zz$Sepal.Length,5.5)
ggplot(data=zz,aes(x=zz_cutvar,color=Species))+geom_density()




#Sample Indexes
indexes = sample(1:nrow(mydata), size=0.33*nrow(mydata))

# Split data
test = mydata[indexes,]
dim(test)  # 6 11
train = mydata[-indexes,]
dim(train) # 26 11

#build a Decision Tree model
mymodel=rpart(formula=price~carat+color+clarity+depth+cut, data=train, method="anova",control=rpart.control(minsplit=50, cp=0.001),parms=list(split="information"))
summary(mymodel)

#Print some model Info
par(xpd = TRUE) 
plot(mymodel, compress = TRUE) 
text(mymodel, use.n = TRUE)
print(mymodel)
plotcp(mymodel)
auc




